# Build for every dongle. TODO TODO TODO this branch should be under slicemk
# parent repo. rename branch too?
include:
  - board: nordic_nrf52840_dongle_slicemk
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_cx_blue
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_rx
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_rx_green
    shield: slicemk_ergodox_dongle
  - board: slicemk_1551usb3_ms88sfa_blue
    shield: slicemk_ergodox_dongle
  - board: slicemk_usbc_mdbt50q_blue
    shield: slicemk_ergodox_dongle
